const USER_CREATION_ERROR = 400;
const INVALID_ID_ERROR = 400;
const INVALID_DATA = 422;
const RESOURCE_NOT_FOUND_ERROR = 404;
const SERVER_ERROR = 500;

module.exports = {
  USER_CREATION_ERROR,
  INVALID_ID_ERROR,
  INVALID_DATA,
  RESOURCE_NOT_FOUND_ERROR,
  SERVER_ERROR,
};
