const ERROR_CODES = {
  INVALID_ID_ERROR: 400,
  USER_CREATION_ERROR: 400,
  INVALID_DATA_ERROR: 400,
  RESOURCE_NOT_FOUND_ERROR: 404,
  UNAUTHORIZED: 401,
  DUPLICATE_EMAIL_ERROR: 409,
  SERVER_ERROR: 500,
};

module.exports = ERROR_CODES;
